# Generated by Django 5.1.3 on 2025-01-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_calories_calories_calorie_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_progress',
            name='weight_lifted',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
