# Generated by Django 5.1.3 on 2025-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_exercise_progress_weight_lifted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_progress',
            name='calories_burned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='bmi',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='bmi_type',
            field=models.CharField(choices=[('uw', 'Under Weight'), ('hw', 'Healthy Weight'), ('ow', 'Over Weight'), ('ob', 'Obesity')], editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(help_text='Height in meters (e.g., 1.80)'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(help_text='Weight in kilograms (e.g., 65)'),
        ),
    ]
