# Generated by Django 5.1.3 on 2025-01-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_weightgoal_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FitnessAnalytics',
        ),
    ]
